name: jackzco3
version: 3.1.0
author: Jackz
main: me.jackz.jackzco3.Main
api-version: 1.14
softdepend: [WorldGuard,GlowAPI,Citizens]
depend: []
commands:
  jackzco:
    description: The main JackzCo command
    usage: /jackzco help
  idmanagement:
    description: ID Card management
    usage: /idm
  getid:
    description: gets a ID card provided by StevesCo
    usage: /getid [level]
  setname:
    description: set item of name
    usage: /setname <name>
  uuid:
    description: prints your uuid
    usage: /uuid [username]
  getlogs:
    description: gets the latest server logs
    usage: /getlogs [# of last lines]
  test:
    description: TEST TEST? TEST TEST! TEST TEST TEST. TEST TEST
    usage: TEST TEST TEST TEST TEST TEST
  getname:
    description: gets the name of the item
    usage: /getitem
  jphone:
    description: the jphone cmd line thingy yeah ha
    usage: /jphone help
  jstore:
    description: open the jstore
    usage: /jstore
  openchant:
    aliases: [opchant]
    description: super enchant
    usage: /openchant <enchantment> <level>
  jboss:
    description: BOSS TIME
    usage: /jboss help
  worlds:
    description: teleport to different worlds
    usage: /worlds