name: jackzco3
version: 3.0.0
author: Jackz
main: me.jackz.jackzco3.Main
softdepend: [WorldGuard]
depend: [TTA]
commands:
  jackzco:
    description: The main JackzCo command
    usage: /jackzco help
  idmanagement:
    description: ID Card management
    usage: /idm
  getid:
    description: gets a ID card provided by StevesCo
    usage: /getid [level]
  setname:
    description: set item of name
    usage: /setname <name>
  uuid:
    description: prints your uuid
    usage: /uuid [username]
  getlogs:
    description: gets the latest server logs
    usage: /getlogs [# of last lines]