name: jackzco3
version: 3.0.0
author: Jackz
main: me.jackzmc.jackzco3.Main
softdepend: [WorldGuard]
depend: [TTA]
commands:
  jackzco:
    description: JackzCo Control JCommand
    usage: /jackzco help
  idmanagement:
    description: ID Card management
    usage: /idm
  getid:
    description: get an id card
    usage: /getid
  setname:
    description: set item of name
    usage: /setname <name>
